# Generated by Django 2.2.7 on 2020-05-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='school_class',
            field=models.IntegerField(choices=[(0, 'Oddział 0'), (1, 'Klasa I'), (2, 'Klasa II'), (3, 'Klasa III'), (4, 'Klasa IV'), (5, 'Klasa V'), (6, 'Klasa VI'), (7, 'Klasa VII'), (8, 'Klasa VIII')], default=0),
        ),
    ]
