# Generated by Django 2.2.7 on 2020-05-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0003_auto_20200524_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='have_job',
            field=models.BooleanField(verbose_name='Praca'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='tel',
            field=models.IntegerField(verbose_name='Telefon'),
        ),
    ]
