# Generated by Django 2.2.7 on 2020-05-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0005_auto_20200528_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='borough',
            field=models.CharField(max_length=64, verbose_name='gmina'),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=64, verbose_name='powiat'),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(max_length=4, null=True, verbose_name='numer mieszkania'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=4, verbose_name='numer domu'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=64, verbose_name='miejscowość'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='numer telefonu'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=64, verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.IntegerField(choices=[(1, 'Wielkopolskie'), (2, 'Kujawsko-pomorskie'), (3, 'Małopolskie'), (4, 'Łódzkie'), (5, 'Dolnośląskie'), (6, 'Lubelskie'), (7, 'Lubuskie'), (8, 'Mazowieckie'), (9, 'Opolskie'), (10, 'Podlaskie'), (11, 'Pomorskie'), (12, 'Śląskie'), (13, 'Podkarpackie'), (14, 'Świętokrzyskie'), (15, 'Warmińsko-Mazurskie'), (16, 'Zachodniopomorskie')], verbose_name='województwo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=64, verbose_name='ulica'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='PESEL',
            field=models.IntegerField(unique=True, verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='application_status',
            field=models.IntegerField(choices=[(1, 'oczekuje'), (2, 'rozpatrzony pozytywnie'), (3, 'odrzucony')], verbose_name='Status aplikacji'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='birthdate',
            field=models.DateField(verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='birthplace',
            field=models.CharField(max_length=64, verbose_name='Miejsce urodzenia'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='catchment_area',
            field=models.BooleanField(verbose_name='Przynależność do rejonu'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='further_information',
            field=models.TextField(verbose_name='Dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='permanent_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent', to='school_office.Address', verbose_name='Adres zamieszkania'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='residential_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residental', to='school_office.Address', verbose_name='Adres zameldowania'),
        ),
    ]
