# Generated by Django 2.2.7 on 2020-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0007_auto_20200530_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nocatchmentareainformation',
            name='siblings',
        ),
        migrations.AddField(
            model_name='nocatchmentareainformation',
            name='have_siblings',
            field=models.BooleanField(default='False', verbose_name='Czy dziecko posiada rodzeństwo?'),
        ),
        migrations.AddField(
            model_name='nocatchmentareainformation',
            name='preschool_years',
            field=models.IntegerField(null=True, verbose_name='Ile lat dziecko uczęszczało do przedszkola?'),
        ),
        migrations.AddField(
            model_name='nocatchmentareainformation',
            name='siblings_info',
            field=models.TextField(null=True, verbose_name='Rodzeństwo (imię, nazwisko, rok urodzenia'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='data_updating',
            field=models.BooleanField(verbose_name='Podawania do wiadomości szkoły wszelkich zmian w podanych wyżej informacjach'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='nonconference',
            field=models.BooleanField(verbose_name='Uczestniczenia w zebraniach rodziców'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='photo_publication',
            field=models.BooleanField(verbose_name='Wyrażam zgodę na publikację zdjęć dziecka z imprez i uroczystości szkolnych na stronie internetowej promującej placówkę oraz w ramach przekazywania informacji o pracy dydaktyczno – wychowawczej szkoły.'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='processing_of_personal_data',
            field=models.BooleanField(verbose_name='Oświadczam pod rygorem odpowiedzialności karnej, że podane informacje są zgodne z aktualnym stanem faktycznym.'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='provision',
            field=models.BooleanField(verbose_name='Wyrażam zgodę na przetwarzanie danych osobowych zawartych w niniejszym dokumencie'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='statutes',
            field=models.BooleanField(verbose_name='Przestrzegania postanowień statutu szkoły'),
        ),
        migrations.AlterField(
            model_name='nocatchmentareainformation',
            name='disabled',
            field=models.BooleanField(verbose_name='Niepełnosprawność w rodzinie'),
        ),
        migrations.AlterField(
            model_name='nocatchmentareainformation',
            name='full_family',
            field=models.IntegerField(choices=[(1, 'Pełna'), (2, 'niepełna'), (3, 'rozbita'), (4, 'inna sytuacja')], verbose_name='Rodzina'),
        ),
        migrations.AlterField(
            model_name='nocatchmentareainformation',
            name='preschool',
            field=models.BooleanField(verbose_name='Czy dziecko uczęszczało do przedszkola'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='catchment_area',
            field=models.BooleanField(verbose_name='Przynależność do obwodu szkoły'),
        ),
    ]
