# Generated by Django 2.2.7 on 2020-06-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0009_auto_20200601_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
