# Generated by Django 2.2.7 on 2020-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0010_auto_20200601_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nocatchmentareainformation',
            name='full_family',
            field=models.IntegerField(choices=[(1, 'Pełna'), (2, 'Niepełna'), (3, 'Rozbita'), (4, 'Inna sytuacja')], verbose_name='Rodzina'),
        ),
    ]
