# Generated by Django 2.2.7 on 2020-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0011_auto_20200604_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='PESEL',
            field=models.CharField(max_length=11, unique=True, verbose_name='PESEL'),
        ),
    ]
