# Generated by Django 2.2.7 on 2020-06-05 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_office', '0012_auto_20200604_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=6, verbose_name='kod pocztowy'),
        ),
    ]
