# Generated by Django 2.2.7 on 2020-06-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0013_auto_20200605_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.IntegerField(choices=[(1, 'oczekuje'), (2, 'rozpatrzony pozytywnie'), (3, 'odrzucony')], default=1, verbose_name='Status aplikacji'),
        ),
    ]
