# Generated by Django 2.2.7 on 2020-06-06 04:35

from django.db import migrations, models
import school_office.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0015_auto_20200606_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='attachment',
            field=models.FileField(null=True, upload_to=school_office.models.app_attachment_directory_path, verbose_name='Załączniki'),
        ),
    ]
