# Generated by Django 2.2.7 on 2020-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_office', '0016_auto_20200606_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=9, null=True, verbose_name='numer telefonu'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='tel',
            field=models.CharField(max_length=9, verbose_name='Telefon'),
        ),
    ]
